'use strict';
require('dotenv').config();
const path=require('node:path');
const crypto=require('node:crypto');
const express=require('express');
const {createClient}=require('@supabase/supabase-js');
const {iso,statementPeriod,dueDateForStatement,currentOpenStatementEnd,closedStatementEnds,daysBetween}=require('./cardLogic');
const PORT=Number(process.env.PORT||10000);
const URL=process.env.SUPABASE_URL;
const KEY=process.env.SUPABASE_PUBLISHABLE_KEY;
const CRON_SECRET=process.env.CRON_SECRET;
const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'8mb'}));
app.use(express.static(path.join(__dirname,'..','public')));
const base=()=>createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const asUser=t=>createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${t}`}}});
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}));
const opts=s=>`HttpOnly; Path=/; SameSite=Lax; Max-Age=${s}; ${process.env.NODE_ENV==='production'?'Secure;':''}`;
function setSession(res,s){res.append('Set-Cookie',`fin_access=${encodeURIComponent(s.access_token)}; ${opts(Math.max(60,s.expires_in||3600))}`);res.append('Set-Cookie',`fin_refresh=${encodeURIComponent(s.refresh_token)}; ${opts(2592000)}`)}
function clearSession(res){res.append('Set-Cookie',`fin_access=; ${opts(0)}`);res.append('Set-Cookie',`fin_refresh=; ${opts(0)}`)}
async function requireUser(req,res,next){try{const c=cookies(req);let access=c.fin_access,user=null;if(access){const {data,error}=await base().auth.getUser(access);if(!error)user=data.user}if(!user&&c.fin_refresh){const {data,error}=await base().auth.refreshSession({refresh_token:c.fin_refresh});if(!error&&data.session){user=data.user;access=data.session.access_token;setSession(res,data.session)}}if(!user)return res.status(401).json({error:'Sesión vencida. Inicia sesión nuevamente.'});req.user=user;req.db=asUser(access);next()}catch(e){res.status(401).json({error:'No fue posible validar la sesión.'})}}
const text=(v,n=180)=>String(v||'').trim().slice(0,n);
const amount=v=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error('Importe inválido');return Math.round(n*100)/100};
const day=(v,d)=>{const n=Number(v??d);if(!Number.isInteger(n)||n<1||n>28)throw new Error('El día debe estar entre 1 y 28');return n};
const target=s=>Number(s.statement_amount??s.calculated_amount??0);
const remaining=s=>Math.max(0,target(s)-Number(s.paid_amount||0));
function txBody(b){const type=['expense','income','refund'].includes(b.type)?b.type:'expense';const pm=type==='income'?(b.payment_method||'transfer'):b.payment_method;if(type!=='income'&&!['cash','debit','credit','transfer'].includes(pm))throw new Error('Selecciona cómo se pagó');if(pm==='credit'&&!b.card_id)throw new Error('Selecciona la tarjeta');return{transaction_date:String(b.transaction_date||new Date().toISOString().slice(0,10)).slice(0,10),type,description:text(b.description,160)||(type==='income'?'Ingreso':'Gasto'),category:text(b.category,80)||'Otros',amount:amount(b.amount),payment_method:pm,card_id:pm==='credit'?b.card_id:null,notes:text(b.notes,500)||null}}
async function upload(db,uid,dataUrl){if(!dataUrl)return null;const m=/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/i.exec(dataUrl);if(!m)throw new Error('Foto inválida');const buf=Buffer.from(m[2],'base64');if(buf.length>5242880)throw new Error('La foto debe pesar menos de 5 MB');const ext=m[1].includes('png')?'png':m[1].includes('webp')?'webp':'jpg';const p=`${uid}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('receipts').upload(p,buf,{contentType:m[1],upsert:false});if(error)throw error;return p}
async function syncOne(db,uid,card,end){const p=statementPeriod(end,card.cutoff_day),a=iso(p.start),b=iso(p.end);const {data:tx,error:e}=await db.from('transactions').select('type,amount').eq('user_id',uid).eq('card_id',card.id).gte('transaction_date',a).lte('transaction_date',b).in('type',['expense','refund']);if(e)throw e;const calc=Math.max(0,(tx||[]).reduce((s,x)=>s+(x.type==='refund'?-Number(x.amount):Number(x.amount)),0));const due=iso(dueDateForStatement(end,card.payment_day));const {data:old,error:o}=await db.from('card_statements').select('*').eq('user_id',uid).eq('card_id',card.id).eq('period_end',b).maybeSingle();if(o)throw o;if(!old){const {data,error}=await db.from('card_statements').insert({user_id:uid,card_id:card.id,period_start:a,period_end:b,due_date:due,calculated_amount:calc,status:calc<=0?'paid':'pending'}).select('*').single();if(error)throw error;return data}const t=old.statement_amount==null?calc:Number(old.statement_amount),paid=Number(old.paid_amount||0);const {data,error}=await db.from('card_statements').update({period_start:a,due_date:due,calculated_amount:calc,status:paid+.005>=t?'paid':'pending',updated_at:new Date().toISOString()}).eq('id',old.id).select('*').single();if(error)throw error;return data}
async function syncAll(db,uid,cards,months=6){const now=new Date().toISOString().slice(0,10);for(const c of cards||[])for(const end of closedStatementEnds(now,c.cutoff_day,months))await syncOne(db,uid,c,end)}
async function openCycle(db,uid,c){const now=new Date().toISOString().slice(0,10),end=currentOpenStatementEnd(now,c.cutoff_day),p=statementPeriod(end,c.cutoff_day);const {data,error}=await db.from('transactions').select('type,amount').eq('user_id',uid).eq('card_id',c.id).gte('transaction_date',iso(p.start)).lte('transaction_date',now).in('type',['expense','refund']);if(error)throw error;return{period_start:iso(p.start),period_end:iso(end),projected_due_date:iso(dueDateForStatement(end,c.payment_day)),accrued:Math.max(0,(data||[]).reduce((s,x)=>s+(x.type==='refund'?-Number(x.amount):Number(x.amount)),0))}}
app.get('/api/health',(_q,r)=>r.json({ok:true,app:'finanzas-mama',time:new Date().toISOString()}));
app.post('/api/auth/signup',async(req,res)=>{try{const email=text(req.body.email,200).toLowerCase(),password=String(req.body.password||'');if(!email||password.length<6)return res.status(400).json({error:'Correo válido y contraseña de al menos 6 caracteres.'});const {data,error}=await base().auth.signUp({email,password});if(error)throw error;if(data.session){setSession(res,data.session);await asUser(data.session.access_token).from('user_settings').upsert({user_id:data.user.id,notification_email:email,email_notifications:true},{onConflict:'user_id'})}res.json({ok:true,needs_confirmation:!data.session,email})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const {data,error}=await base().auth.signInWithPassword({email:text(req.body.email,200).toLowerCase(),password:String(req.body.password||'')});if(error)throw error;setSession(res,data.session);await asUser(data.session.access_token).from('user_settings').upsert({user_id:data.user.id,notification_email:data.user.email,email_notifications:true},{onConflict:'user_id',ignoreDuplicates:true});res.json({ok:true})}catch(e){res.status(400).json({error:'Correo o contraseña incorrectos.'})}});
app.post('/api/auth/logout',(_q,r)=>{clearSession(r);r.json({ok:true})});
app.get('/api/me',requireUser,async(req,res)=>{const {data}=await req.db.from('user_settings').select('*').eq('user_id',req.user.id).maybeSingle();res.json({user:{id:req.user.id,email:req.user.email},settings:data||{notification_email:req.user.email,email_notifications:true}})});
app.put('/api/settings',requireUser,async(req,res)=>{const row={user_id:req.user.id,notification_email:text(req.body.notification_email,200)||req.user.email,email_notifications:req.body.email_notifications!==false,updated_at:new Date().toISOString()};const {data,error}=await req.db.from('user_settings').upsert(row,{onConflict:'user_id'}).select('*').single();if(error)return res.status(400).json({error:error.message});res.json(data)});
app.get('/api/cards',requireUser,async(req,res)=>{const {data,error}=await req.db.from('credit_cards').select('*').eq('user_id',req.user.id).order('created_at');if(error)return res.status(500).json({error:error.message});res.json(data||[])});
app.post('/api/cards',requireUser,async(req,res)=>{try{const row={user_id:req.user.id,name:text(req.body.name,100)||'Mi tarjeta',bank:text(req.body.bank,100)||null,last4:/^\d{4}$/.test(String(req.body.last4||''))?String(req.body.last4):null,cutoff_day:day(req.body.cutoff_day,15),payment_day:day(req.body.payment_day,3),credit_limit:req.body.credit_limit?Number(req.body.credit_limit):null};const {data,error}=await req.db.from('credit_cards').insert(row).select('*').single();if(error)throw error;res.json(data)}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/cards/:id',requireUser,async(req,res)=>{try{const row={name:text(req.body.name,100)||'Mi tarjeta',bank:text(req.body.bank,100)||null,last4:/^\d{4}$/.test(String(req.body.last4||''))?String(req.body.last4):null,cutoff_day:day(req.body.cutoff_day,15),payment_day:day(req.body.payment_day,3),credit_limit:req.body.credit_limit?Number(req.body.credit_limit):null};const {data,error}=await req.db.from('credit_cards').update(row).eq('id',req.params.id).eq('user_id',req.user.id).select('*').single();if(error)throw error;res.json(data)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/transactions',requireUser,async(req,res)=>{let q=req.db.from('transactions').select('*,credit_cards(name,last4),transaction_items(*)').eq('user_id',req.user.id).order('transaction_date',{ascending:false}).order('created_at',{ascending:false}).limit(300);if(/^\d{4}-\d{2}$/.test(req.query.month||'')){const [y,m]=req.query.month.split('-').map(Number);q=q.gte('transaction_date',`${req.query.month}-01`).lte('transaction_date',new Date(Date.UTC(y,m,0,12)).toISOString().slice(0,10))}const {data,error}=await q;if(error)return res.status(500).json({error:error.message});res.json(data||[])});
app.post('/api/transactions',requireUser,async(req,res)=>{let receipt=null;try{const row=txBody(req.body);receipt=await upload(req.db,req.user.id,req.body.receipt_base64);const {data,error}=await req.db.from('transactions').insert({...row,user_id:req.user.id,receipt_path:receipt}).select('*').single();if(error)throw error;res.json(data)}catch(e){if(receipt)await req.db.storage.from('receipts').remove([receipt]);res.status(400).json({error:e.message})}});
app.put('/api/transactions/:id',requireUser,async(req,res)=>{try{const {data,error}=await req.db.from('transactions').update(txBody(req.body)).eq('id',req.params.id).eq('user_id',req.user.id).select('*').single();if(error)throw error;res.json(data)}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/transactions/:id',requireUser,async(req,res)=>{const {data:t}=await req.db.from('transactions').select('receipt_path').eq('id',req.params.id).eq('user_id',req.user.id).maybeSingle();const {error}=await req.db.from('transactions').delete().eq('id',req.params.id).eq('user_id',req.user.id);if(error)return res.status(400).json({error:error.message});if(t?.receipt_path)await req.db.storage.from('receipts').remove([t.receipt_path]);res.json({ok:true})});
app.get('/api/transactions/:id/receipt',requireUser,async(req,res)=>{const {data:t}=await req.db.from('transactions').select('receipt_path').eq('id',req.params.id).eq('user_id',req.user.id).maybeSingle();if(!t?.receipt_path)return res.status(404).json({error:'Ticket no encontrado'});const {data,error}=await req.db.storage.from('receipts').createSignedUrl(t.receipt_path,300);if(error)return res.status(500).json({error:error.message});res.json({url:data.signedUrl})});
app.get('/api/dashboard',requireUser,async(req,res)=>{try{const now=new Date(),month=now.toISOString().slice(0,7),[y,m]=month.split('-').map(Number),start=`${month}-01`,end=new Date(Date.UTC(y,m,0,12)).toISOString().slice(0,10);const [{data:txs,error:e1},{data:cards,error:e2}]=await Promise.all([req.db.from('transactions').select('*').eq('user_id',req.user.id).gte('transaction_date',start).lte('transaction_date',end),req.db.from('credit_cards').select('*').eq('user_id',req.user.id).eq('is_active',true).order('created_at')]);if(e1||e2)throw(e1||e2);await syncAll(req.db,req.user.id,cards,4);const {data:sts,error:e3}=await req.db.from('card_statements').select('*,credit_cards(name,last4)').eq('user_id',req.user.id).order('due_date');if(e3)throw e3;let income=0,expenses=0,refunds=0;const cats={};for(const t of txs||[]){if(t.type==='income')income+=Number(t.amount);if(t.type==='expense'){expenses+=Number(t.amount);cats[t.category]=(cats[t.category]||0)+Number(t.amount)}if(t.type==='refund')refunds+=Number(t.amount)}const cycles=[];for(const card of cards||[])cycles.push({card,cycle:await openCycle(req.db,req.user.id,card)});const today=now.toISOString().slice(0,10),upcoming=(sts||[]).map(s=>({...s,remaining:remaining(s),target_amount:target(s)})).filter(s=>s.status!=='paid'&&s.remaining>0&&daysBetween(today,s.due_date)>=-10).sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,6);res.json({month,summary:{income,expenses:Math.max(0,expenses-refunds),balance:income-expenses+refunds},by_category:Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,8),upcoming,card_cycles:cycles})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/statements',requireUser,async(req,res)=>{try{const {data:cards,error:e}=await req.db.from('credit_cards').select('*').eq('user_id',req.user.id);if(e)throw e;await syncAll(req.db,req.user.id,cards,8);const {data,error}=await req.db.from('card_statements').select('*,credit_cards(name,last4)').eq('user_id',req.user.id).order('period_end',{ascending:false}).limit(50);if(error)throw error;res.json((data||[]).map(s=>({...s,target_amount:target(s),remaining:remaining(s)})))}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/statements/:id/amount',requireUser,async(req,res)=>{try{const v=req.body.statement_amount===''||req.body.statement_amount==null?null:amount(req.body.statement_amount);const {data:s,error:e}=await req.db.from('card_statements').select('*').eq('id',req.params.id).eq('user_id',req.user.id).single();if(e)throw e;const t=v??Number(s.calculated_amount),status=Number(s.paid_amount||0)+.005>=t?'paid':'pending';const {data,error}=await req.db.from('card_statements').update({statement_amount:v,status,updated_at:new Date().toISOString()}).eq('id',s.id).select('*').single();if(error)throw error;res.json({...data,target_amount:target(data),remaining:remaining(data)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/statements/:id/pay',requireUser,async(req,res)=>{try{const paidNow=amount(req.body.amount),date=String(req.body.payment_date||new Date().toISOString().slice(0,10)).slice(0,10);const {data:s,error:e}=await req.db.from('card_statements').select('*').eq('id',req.params.id).eq('user_id',req.user.id).single();if(e)throw e;const {error:p}=await req.db.from('card_payments').insert({user_id:req.user.id,card_id:s.card_id,statement_id:s.id,payment_date:date,amount:paidNow,notes:text(req.body.notes,300)||null});if(p)throw p;const paid=Number(s.paid_amount||0)+paidNow,status=paid+.005>=target(s)?'paid':'pending';const {data,error}=await req.db.from('card_statements').update({paid_amount:paid,status,updated_at:new Date().toISOString()}).eq('id',s.id).select('*').single();if(error)throw error;res.json({...data,target_amount:target(data),remaining:remaining(data)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/reminders/run',async(req,res)=>{if(!CRON_SECRET||req.headers['x-cron-secret']!==CRON_SECRET)return res.status(401).json({error:'No autorizado'});try{const r=await fetch(`${URL}/functions/v1/finance-reminders`,{method:'POST',headers:{'content-type':'application/json','apikey':KEY,'x-cron-secret':CRON_SECRET},body:'{}'});const d=await r.json().catch(()=>({}));res.status(r.status).json(d)}catch(e){res.status(500).json({error:e.message})}});
app.use((_q,r)=>r.sendFile(path.join(__dirname,'..','public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Mis Finanzas listo en ${PORT}`));
